### ISSUE TITLE
Changing color of package version on navigation bar to make it more visible

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystatstemplate#1]
The [CSS](https://github.com/easystats/easystatstemplate/blob/main/inst/pkgdown/BS5/extra.scss) needs to be tweaked to resolve this, but I tried a few things and nothing seem to work.

As seen on the homepage of _datawizard_: https://easystats.github.io/datawizard/

<img width="479" alt="Screenshot 2022-08-11 at 10 30 32" src="https://user-images.githubusercontent.com/11330453/184094480-b4835b66-cb87-4ce5-a23c-5dd60afe05ea.png">

@etiennebacher Can you have a look at?

**Comment by IndrajeetPatil** [comment]
Seems to be working. Thanks!!!

**Comment by etiennebacher** [comment]
Fixed

![image](https://user-images.githubusercontent.com/52219252/184102904-763708fb-abc9-48da-82e0-7599b3e116dd.png)
