### ISSUE TITLE
Check out why `dt` element doesn't respect `text-indent` property

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystatstemplate#3]
https://easystats.github.io/datawizard/reference/index.html

<img width="681" alt="Screenshot 2022-09-02 at 20 52 22" src="https://user-images.githubusercontent.com/11330453/188219220-668c51ac-15a7-4ddc-9533-026a7b0caffb.png">

**Comment by IndrajeetPatil** [comment]
CSS rule is defined here:

https://github.com/easystats/easystatstemplate/blob/db2f02eb7c7e67d2b45c732b7355accf80203f0f/inst/pkgdown/BS5/extra.scss#L37-L43

**Comment by strengejacke** [comment]
maybe try `dt` instead `dl`?

**Comment by strengejacke** [comment]
Or maybe even remove that completely:


https://user-images.githubusercontent.com/26301769/188268670-66826f6f-27bb-434c-8285-2c1cba0321ab.mp4

**Comment by IndrajeetPatil** [comment]
Bootstrap doesn't do it by default. That's the customization I introduced because I like the idea of visually grouping similar things by indenting them.

You don't like it? Happy to revert it.

**Comment by strengejacke** [comment]
No, I just thought you were asking how to fix this. I don't mind if the complete section is indented or not ;-)
Maybe https://www.geeksforgeeks.org/how-to-set-indent-the-second-line-of-paragraph-using-css/?

**Comment by strengejacke** [comment]
Seems to work now:

![image](https://user-images.githubusercontent.com/26301769/188302244-a5c1a952-ebe4-4905-963d-96a28cf8f749.png)

**Comment by IndrajeetPatil** [comment]
Ah, yes, worked on this yesterday but forgot to close the issue.

Thanks for confirming!

**Comment by strengejacke** [comment]
Oh, you did? For me, the page wasn't rendering properly (maybe a cache issue?), and I just committed a different try to the CSS-file. 😬 

So did both, your commit and mine work?

**Comment by IndrajeetPatil** [comment]
LOL

I think yours might be the one that must have fixed it. 

Last night it wasn't working but when you said it was, I thought I was the one who was looking at the cached version of the website. 

Thanks!!
