### ISSUE TITLE
What's up with the extra left margin (?) in index pages?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystatstemplate#4]
cf. https://easystats.github.io/correlation/reference/index.html (contrast with https://pkgdown.r-lib.org/reference/index.html)

<img width="1440" alt="Screenshot 2023-02-13 at 13 47 29" src="https://user-images.githubusercontent.com/11330453/218461683-6ab27cba-1475-484b-89f5-0c64781d4fd9.png">

**Comment by IndrajeetPatil** [comment]
Confirmed in Chrome and Safari on Desktop.

**Comment by etiennebacher** [comment]
I don't have this problem (Windows + Firefox):

![image](https://user-images.githubusercontent.com/52219252/218524805-809641dd-977a-4aa4-bf3d-1ed1e96a40fe.png)

![image](https://user-images.githubusercontent.com/52219252/218524830-b8fe24bb-2990-4317-b0fe-4e3d3c424950.png)

**Comment by strengejacke** [comment]
I don't see this issue, either. Maybe it's a Mac thing, so can safely be ignored?

**Comment by IndrajeetPatil** [comment]
Strange. Maybe it's not even Mac, and just my laptop. At any rate, can be ignored for now.
