### ISSUE TITLE
Search box has disappeared from all websites

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystatstemplate#5]
cc @etiennebacher; in case you find time before me to have a look at this :)

**Comment by strengejacke** [comment]
Which one do you mean? I see this here for _parameters_:

![image](https://github.com/easystats/easystatstemplate/assets/26301769/51c5d5f4-f554-48dc-aa29-3072f45cab3a)

**Comment by etiennebacher** [comment]
Not all of them are concerned, I think only those that were rebuilt recently (today?). There's a lot of recent activity in `pkgdown` and we use the github version in the workflow (https://github.com/easystats/insight/actions/runs/8767294218/job/24060377877#step:6:15095), that's probably the cause

**Comment by strengejacke** [comment]
> Failed to get R release: Failed to get R 4.3.3

Yeah, all R versions are being updated (R 4.4 is now release, R 4.5 is devel), maybe that's a reason.

**Comment by etiennebacher** [comment]
No I mean that `pkgdown` itself has updates: https://github.com/r-lib/pkgdown/commits/main/

I don't think it's related to the R version (also I don't know where the quote in your message comes from)

**Comment by strengejacke** [comment]
https://github.com/strengejacke/ggeffects/actions/runs/8814768041/job/24196603872

**Comment by strengejacke** [comment]
> No I mean that `pkgdown` itself has updates: https://github.com/r-lib/pkgdown/commits/main/
> 
> I don't think it's related to the R version

Makes sense.

**Comment by IndrajeetPatil** [comment]
I doubt that explains it because I build _statsExpressions_ and _ggstatsplot_ package websites also with devel-_pkgdown_, and I don't see any issues in the search box for these websites.

**Comment by etiennebacher** [comment]
Yes but depending on the time at which you build the website, you don't include the same commits. I'm not saying that's 100% the cause, I didn't check, but is there any reason why we use the devel version?

**Comment by strengejacke** [comment]
Developers always use devel versions. 
![image](https://github.com/easystats/easystatstemplate/assets/26301769/dcdf5b3f-b0ab-4e25-84fb-ca5a73ec6204)

**Comment by IndrajeetPatil** [comment]
Yes, that has always been the case. I would prefer to get the latest pkgdown features to build our websites. It has rarely bitten us, and it's fine even if we get bitten once in a while; it's worth the cost.

**Comment by IndrajeetPatil** [comment]
I built ggstatsplot website an hour ago and search box is fine:

https://indrajeetpatil.github.io/ggstatsplot/

**Comment by IndrajeetPatil** [comment]
Should be fixed now. Just need to rebuild the websites, but that should happen automatically the next time you commit something.
