### ISSUE TITLE
Light theme - version number hardly visible

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystatstemplate#8]
Maybe a regression of #7?
For light theme, the version number is hardly visible:

![image](https://github.com/easystats/easystatstemplate/assets/26301769/a0eba8cf-842d-48fb-9134-086507267ad4)

**Comment by IndrajeetPatil** [comment]
Must have been a temporary issue:

<img width="109" alt="Screenshot 2024-07-18 at 12 23 53" src="https://github.com/user-attachments/assets/382e5d91-2e3f-436c-b174-10fee92307cc">
